/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze News
         * @description Encola el análisis de una noticia y devuelve su id en estado ``pending``.
         */
        post: operations["analyze_news_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Pdf
         * @description Sube un PDF, guarda el binario y encola su análisis en estado ``pending``.
         */
        post: operations["analyze_pdf_analysis_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Detail
         * @description Endpoint para obtener un análisis específico del usuario autenticado.
         */
        get: operations["get_analysis_detail_analysis__analysis_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Analysis Detail
         * @description Elimina un análisis del usuario autenticado.
         */
        delete: operations["delete_analysis_detail_analysis__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{analysis_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Pdf File
         * @description Devuelve el PDF original de un análisis para mostrarlo en el informe.
         */
        get: operations["get_analysis_pdf_file_analysis__analysis_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{analysis_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Analysis
         * @description Reabre un análisis ``failed`` propio y lo reencola reutilizando su entrada.
         */
        post: operations["retry_analysis_analysis__analysis_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Summary
         * @description Endpoint para obtener métricas agregadas del dashboard del usuario.
         */
        get: operations["get_dashboard_summary_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Endpoint para listar el historial de análisis del usuario autenticado.
         */
        get: operations["get_history_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export History
         * @description Exporta todo el historial filtrado del usuario como un fichero CSV.
         */
        get: operations["export_history_history_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Comprueba que todos los servicios están activos. Devuelve
         *     503 salvo que la cola, la base de datos y Redis respondan.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisHistoryItem
         * @description Modelo de datos para un ítem del historial de análisis.
         */
        AnalysisHistoryItem: {
            /** Analysis Id */
            analysis_id: string;
            /** User Id */
            user_id: string;
            /** Source Type */
            source_type: string;
            /** Input Text */
            input_text?: string | null;
            /** Input Url */
            input_url?: string | null;
            /** Label */
            label?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Explanation */
            explanation?: string | null;
            /**
             * Status
             * @default done
             */
            status: string;
            /** Error Code */
            error_code?: string | null;
            /** Created At */
            created_at: string;
            /** Pdf Filename */
            pdf_filename?: string | null;
            /** Claims */
            claims?: components["schemas"]["ClaimItem"][] | null;
            /** Sources */
            sources?: components["schemas"]["SourceItem"][] | null;
            /**
             * Verdict
             * @description Bucket del veredicto (`real`/`fake`/`uncertain`) derivado de la etiqueta.
             * @enum {string}
             */
            readonly verdict: "real" | "fake" | "uncertain";
            /**
             * Credibility
             * @description Credibilidad [0, 100] derivada del veredicto y la confianza.
             */
            readonly credibility: number | null;
        };
        /**
         * AnalysisRequest
         * @description Modelo de datos para la solicitud de análisis.
         */
        AnalysisRequest: {
            /** Text */
            text?: string | null;
            /** Url */
            url?: string | null;
            /** @default text */
            source_type: components["schemas"]["SourceType"];
        };
        /**
         * AnalysisResponse
         * @description Modelo de datos para la respuesta del análisis.
         */
        AnalysisResponse: {
            /** Status */
            status: string;
            /** Analysis Id */
            analysis_id?: string | null;
            /** Message */
            message?: string | null;
            /** Label */
            label?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Explanation */
            explanation?: string | null;
        };
        /** Body_analyze_pdf_analysis_pdf_post */
        Body_analyze_pdf_analysis_pdf_post: {
            /** File */
            file: string;
        };
        /**
         * ClaimItem
         * @description Veredicto de una afirmación concreta dentro de un análisis.
         */
        ClaimItem: {
            /** Text */
            text: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /**
             * Verdict
             * @description Bucket del veredicto (`real`/`fake`/`uncertain`) derivado de la etiqueta.
             * @enum {string}
             */
            readonly verdict: "real" | "fake" | "uncertain";
        };
        /**
         * DashboardAlertItem
         * @description Modelo de datos para un ítem de alerta en el dashboard.
         */
        DashboardAlertItem: {
            /** Id */
            id: string;
            /** Source Type */
            source_type: string;
            /** Input Text */
            input_text?: string | null;
            /** Input Url */
            input_url?: string | null;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /** Created At */
            created_at: string;
            /**
             * Credibility
             * @description Credibilidad [0, 100] derivada del veredicto y la confianza.
             */
            readonly credibility: number | null;
        };
        /**
         * DashboardDomainBreakdownItem
         * @description Modelo de datos para un ítem de desglose por dominio en el dashboard.
         */
        DashboardDomainBreakdownItem: {
            /** Domain */
            domain: string;
            /** Total */
            total: number;
            /** Average Confidence */
            average_confidence: number;
        };
        /**
         * DashboardKpis
         * @description Modelo de datos para los KPIs del dashboard.
         */
        DashboardKpis: {
            /** Total Analyses */
            total_analyses: number;
            /** Reliable Rate */
            reliable_rate: number;
            /** Average Confidence */
            average_confidence: number;
            /** Week Over Week Delta */
            week_over_week_delta: number;
        };
        /**
         * DashboardSourceBreakdownItem
         * @description Modelo de datos para un ítem de desglose por fuente en el dashboard.
         */
        DashboardSourceBreakdownItem: {
            /** Source Type */
            source_type: string;
            /** Total */
            total: number;
            /** Average Confidence */
            average_confidence: number;
        };
        /**
         * DashboardSummaryResponse
         * @description Modelo de datos para el resumen del dashboard.
         */
        DashboardSummaryResponse: {
            /** Status */
            status: string;
            kpis: components["schemas"]["DashboardKpis"];
            /** Trend */
            trend: components["schemas"]["DashboardTrendPoint"][];
            /** Source Breakdown */
            source_breakdown: components["schemas"]["DashboardSourceBreakdownItem"][];
            /** Domain Breakdown */
            domain_breakdown: components["schemas"]["DashboardDomainBreakdownItem"][];
            /** Alerts */
            alerts: components["schemas"]["DashboardAlertItem"][];
        };
        /**
         * DashboardTrendPoint
         * @description Modelo de datos para un punto de tendencia en el dashboard.
         */
        DashboardTrendPoint: {
            /** Date */
            date: string;
            /** Total */
            total: number;
            /** Average Confidence */
            average_confidence: number;
        };
        /**
         * ErrorCode
         * @description Códigos estables que el frontend puede usar para identificar errores.
         * @enum {string}
         */
        ErrorCode: "CONNECTION" | "INTERNAL" | "NO_MEDICAL_CLAIMS" | "ANALYSIS_SAVE_FAILED" | "SERVICE_UNAVAILABLE" | "URL_EXTRACTION" | "INVALID_PDF" | "PDF_TOO_LARGE" | "PDF_EXTRACTION" | "INVALID_ANALYSIS_ID" | "ANALYSIS_NOT_FOUND" | "ANALYSIS_FETCH_FAILED" | "ANALYSIS_DELETE_FAILED" | "ANALYSIS_NOT_RETRYABLE" | "ANALYSIS_RETRY_FAILED" | "HISTORY_FETCH_FAILED" | "DASHBOARD_FETCH_FAILED" | "RATE_LIMIT" | "UNAUTHENTICATED" | "INVALID_TOKEN" | "EXPIRED_TOKEN";
        /**
         * ErrorDetail
         * @description Forma del campo `detail` que se envía en HTTPException.
         */
        ErrorDetail: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description Cuerpo completo de un error: {"detail": ErrorDetail}.
         *
         *     Se usa en el parámetro ``responses`` de las rutas para documentar el
         *     contrato de errores en OpenAPI y, vía openapi-typescript, en el frontend.
         */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryResponse
         * @description Modelo de datos para la respuesta del endpoint de historial de análisis.
         */
        HistoryResponse: {
            /** Status */
            status: string;
            /** Items */
            items: components["schemas"]["AnalysisHistoryItem"][];
            /** Count */
            count: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * SourceItem
         * @description Fuente de literatura biomédica recuperada para fundamentar el análisis.
         */
        SourceItem: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source */
            source?: string | null;
            /** Year */
            year?: string | null;
            /** Statements */
            statements?: string[] | null;
        };
        /**
         * SourceType
         * @description Tipos de fuentes de entrada para el análisis.
         * @enum {string}
         */
        SourceType: "text" | "file" | "url" | "pdf";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_news_analysis_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyze_pdf_analysis_pdf_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_pdf_analysis_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_analysis_detail_analysis__analysis_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisHistoryItem"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_analysis_detail_analysis__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_analysis_pdf_file_analysis__analysis_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF original. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_analysis_analysis__analysis_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dashboard_summary_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_history_history_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                source_type?: "all" | "text" | "file" | "url";
                date_range?: "all" | "7d" | "30d" | "90d";
                date_sort?: "desc" | "asc";
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_history_history_export_get: {
        parameters: {
            query?: {
                search?: string | null;
                source_type?: "all" | "text" | "file" | "url";
                date_range?: "all" | "7d" | "30d" | "90d";
                date_sort?: "desc" | "asc";
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial en formato CSV. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
